//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BirdManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cage
    {
        public int Id { get; set; }
        public string SerialNumber { get; set; }
        public double Width { get; set; }
        public double Length { get; set; }
        public double Height { get; set; }
        public string CageMaterial { get; set; }
    }
}
